### ISSUE TITLE
XrayR配置REALITY启动不成功

### ISSUE THREAD

**Issue by nianqianku** [ppoonk/XrayR-for-AirGo#1]
日志如下
Nov 19 14:38:33 debian systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 4.
Nov 19 14:38:33 debian systemd[1]: Stopped XrayR Service.
Nov 19 14:38:33 debian systemd[1]: Started XrayR Service.
Nov 19 14:38:33 debian XrayR[2271674]: XrayR 0.9.2 (A Xray backend that supports many panels)
Nov 19 14:38:33 debian XrayR[2271674]: 2023/11/19 14:38:33 Start the panel..
Nov 19 14:38:33 debian XrayR[2271674]: 2023/11/19 14:38:33 Xray Core Version: 1.8.4
Nov 19 14:38:33 debian XrayR[2271674]: 2023/11/19 14:38:33 [Warning] core: Xray 1.8.4 started
Nov 19 14:38:34 debian XrayR[2271674]: 2023/11/19 14:38:34 infra/conf: REALITY only supports TCP, H2, gRPC and DomainSocket for now.
Nov 19 14:38:34 debian XrayR[2271674]: panic: infra/conf: REALITY only supports TCP, H2, gRPC and DomainSocket for now.
Nov 19 14:38:34 debian XrayR[2271674]: goroutine 1 [running]:
Nov 19 14:38:34 debian XrayR[2271674]: log.Panic({0xc0007959e8?, 0xc0004dae00?, 0xc000795a68?})
Nov 19 14:38:34 debian XrayR[2271674]:         log/log.go:432 +0x5a
Nov 19 14:38:34 debian XrayR[2271674]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0004db700)
Nov 19 14:38:34 debian XrayR[2271674]:         github.com/XrayR-project/XrayR/service/controller/controller.go:88 +0x26f
Nov 19 14:38:34 debian XrayR[2271674]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0004a2000)
Nov 19 14:38:34 debian XrayR[2271674]:         github.com/XrayR-project/XrayR/panel/panel.go:197 +0x50d
Nov 19 14:38:34 debian XrayR[2271674]: github.com/XrayR-project/XrayR/cmd.run()
Nov 19 14:38:34 debian XrayR[2271674]:         github.com/XrayR-project/XrayR/cmd/root.go:94 +0x233
Nov 19 14:38:34 debian XrayR[2271674]: github.com/XrayR-project/XrayR/cmd.glob..func1(0xc0004da800?, {0x357f4c8?, 0x4?, 0x357f4cc?})
Nov 19 14:38:34 debian XrayR[2271674]:         github.com/XrayR-project/XrayR/cmd/root.go:26 +0x13
Nov 19 14:38:34 debian XrayR[2271674]: github.com/spf13/cobra.(*Command).execute(0x5c17a20, {0xc000136060, 0x0, 0x0})
Nov 19 14:38:34 debian XrayR[2271674]:         github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
Nov 19 14:38:34 debian XrayR[2271674]: github.com/spf13/cobra.(*Command).ExecuteC(0x5c17a20)
Nov 19 14:38:34 debian XrayR[2271674]:         github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
Nov 19 14:38:34 debian XrayR[2271674]: github.com/spf13/cobra.(*Command).Execute(...)
Nov 19 14:38:34 debian XrayR[2271674]:         github.com/spf13/cobra@v1.7.0/command.go:992
Nov 19 14:38:34 debian XrayR[2271674]: github.com/XrayR-project/XrayR/cmd.Execute(...)
Nov 19 14:38:34 debian XrayR[2271674]:         github.com/XrayR-project/XrayR/cmd/root.go:108
Nov 19 14:38:34 debian XrayR[2271674]: main.main()
Nov 19 14:38:34 debian XrayR[2271674]:         github.com/XrayR-project/XrayR/main.go:10 +0x1a
Nov 19 14:38:34 debian systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 19 14:38:34 debian systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by ppoonk** [comment]
报错信息：REALITY only supports TCP, H2, gRPC and DomainSocket for now，web管理界面请选择tcp协议
